server:
  port: 8081

app:
  security:
    jwt:
      secret: ${APP_JWT_SECRET:ZGVtby1tdG8tand0LXNlY3JldC1rZXktbm90LWZvci1wcm9kdWN0aW9u}

spring:
  application:
    name: projection-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/projectiondb}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: projection-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
