server:
  port: 8080

app:
  security:
    jwt:
      secret: ${APP_JWT_SECRET:ZGVtby1tdG8tand0LXNlY3JldC1rZXktbm90LWZvci1wcm9kdWN0aW9u}
    credentials:
      username: ${APP_CREDENTIALS_USERNAME:admin}
      password: ${APP_CREDENTIALS_PASSWORD:admin}

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
